//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simpson_Group_Store_Database.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int Errorid { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
