//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simpson_Group_Store_Database.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginResult
    {
        public int LoginResultid { get; set; }
        public int Userid { get; set; }
        public bool Result { get; set; }
        public System.DateTime DateTime { get; set; }
        public string ipaddress { get; set; }
    
        public virtual User User { get; set; }
    }
}
