//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simpson_Group_Store_Database.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Addresses = new HashSet<Address>();
            this.LoginResults = new HashSet<LoginResult>();
            this.Orders = new HashSet<Order>();
        }
    
        public int Userid { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public System.DateTime DoB { get; set; }
        public System.DateTime Registered { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<LoginResult> LoginResults { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Password Password { get; set; }
        public virtual Session Session { get; set; }
    }
}
